logging:
  level:
    root: info
    com.larastudios: debug
    com.larastudios.chambrier.app.flowEngine: info

spring:
  profiles:
    default: local
  codec:
    max-in-memory-size: 1MB

flows:
  directory: /etc/chambrier/flows

hue:
  enabled: false
  base-url: ${HUE_ENDPOINT}
  app-key: ${HUE_APP_KEY}
