logging:
  level:
    root: info
    com.larastudios: debug

spring:
  profiles:
    default: local
  codec:
    max-in-memory-size: 1MB

hue:
  enabled: false
  base-url: ${HUE_ENDPOINT}
  app-key: ${HUE_APP_KEY}
