logging:
  level:
    root: info
    com.larastudios: debug
    com.larastudios.chambrier.app.flowEngine: info
    javax.jmdns.impl.DNSIncoming: error

server:
  port: 8080
  shutdown: "graceful"

spring:
  profiles:
    default: local
  codec:
    max-in-memory-size: 1MB

resilience4j.ratelimiter:
  instances:
    hue:
      limitForPeriod: 1
      limitRefreshPeriod: 100ms
      timeoutDuration: 200ms
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

flows:
  directory: /etc/chambrier/flows

hue:
  enabled: false
  base-url: ${HUE_ENDPOINT}
  app-key: ${HUE_APP_KEY}

shelly:
  enabled: false
